### ISSUE TITLE
Alpha v2 Release

### ISSUE THREAD

**Issue by jscottsmith** [jscottsmith/react-scroll-parallax#15]
### Why?

[v2](https://github.com/jscottsmith/react-scroll-parallax/tree/v2) is a re-write of v1 to add new scroll effects such as opacity and scale in addition to translations. It also uses the new [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) which is a more efficient way of determining when elements are within the viewport as compared with v1's implementation. Additionally, much of the state of v1's ParallaxController has been moved to focused React components with the hope that these components can also be repurposed to create additional effects. This also has the added benefit of being able to easily debug with React specific tooling to see the state of effects in the browser.

### Installation

Currently pre-releases can be [installed](https://github.com/jscottsmith/react-scroll-parallax/tree/v2#install) via `react-scroll-parallax@next`. But note this is an **alpha** and subject to breaking changes -- it should not be used in production.

### Demos

Take a look at the [Storybook Demos](http://react-scroll-parallax.surge.sh) for various implementations with v2 prop API. Toggle knobs to change the props on the fly.

### Todo List

Tasks that still need to be completed for a proper Beta release:

- [ ] Add additional stories
- [ ] Update old example sites to use v2
- [x] Remove debug styles
- [ ] Increase test coverage
- [ ] Review and update the README
- [ ] Add an ISSUE_TEMPLATE
- [ ] Add `disabled` prop
- [ ] Document _all_ props
- [ ] Add an example of how to update cached properties
- [ ] Document internal components that can be used without parallax such as `<Observed>`
- [x] Expose `progress` value in the render function
- [ ] Consider adding an illustration that details how this lib works (x, y offsets)
- [ ] Consider additional components like `<ParallaxImage>` or `<ParallaxBanner>`
- [ ] Consider prop config to determine how `progress` is calculated for special use cases #21
- [ ] Consider adding a specialized component that supports parallax of fixed position elements. See #23

### Requests

Any feature requests, concerns, or changes to the current API can be discussed here.

**Comment by lsirivong** [comment]
Cool stuff! Have you considered having a way to expose this `[progress](https://github.com/jscottsmith/react-scroll-parallax/blob/v2/src/components/Parallax.js#L86-L87)` value down directly into the children render function?

If that's possible you wouldn't have to chase down every style usecase (for example, if someone wanted to do a `rotate`).

**Comment by jscottsmith** [comment]
@lsirivong Yup, should be really easy. I'll add it to the list.

**Comment by JulianJorgensen** [comment]
Really awesome! This library is really needed in the react community.

I've done a test run of v2 and works great except the scroll effect values start with a offset. Not sure how to turn the offset off. 
I'd expect the content of following to start at a full opacity (1) and then 0 when it is not in view.
```
<Parallax
  opacity={[1, 0]}
>
```

However, it starts at around 0.6 opacity even with the scrollbar all the way to the top.

Is this just a alpha bug, or am I missing something?

**Comment by JulianJorgensen** [comment]
Would also be fantastic to have a `onVisibilityChange` prop on `<parallax>`. That way we can call methods when visibility changes, as opposed to just renders.

**Comment by jscottsmith** [comment]
@JulianJorgensen 
> it starts at around 0.6 opacity even with the scrollbar all the way to the top.

It depends where the element is within the viewport, not only the page's scroll position. If it's sitting about midway from the top and bottom, then yes, `0.6` is probably the expected opacity. With these props `[1, 0]` I would expect it to be completely opaque as it enters the bottom of the window, then be completely transparent as it leaves. Which will look like the A element on this [story](http://react-scroll-parallax.surge.sh/?knob-A%3A%20Opacity%201=1&knob-A%3A%20Opacity%202=0&knob-B%3A%20Opacity%201=0&knob-B%3A%20Opacity%202=1&selectedKind=%3CParallax%3E&selectedStory=with%20opacity%20props&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs). If this still appears to be a bug in your situation please share some code with me so I can take a look.

> Would also be fantastic to have a onVisibilityChange prop on `<parallax>`. That way we can call methods when visibility changes, as opposed to just renders.

You can currently access the visibility of a `<Parallax>` element with a [render callback](http://react-scroll-parallax.surge.sh/?knob-A%3A%20Opacity%201=1&knob-A%3A%20Opacity%202=0&knob-B%3A%20Opacity%201=0&knob-B%3A%20Opacity%202=1&selectedKind=%3CParallax%3E&selectedStory=with%20opacity%20props&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs). If you needed a method to be called you could add one to a child component that takes the `isInView` bool as a prop that then calls the method you need in a lifecycle hook when it changes.

**Comment by PTcampbell** [comment]
+1 to the Opacity offset – I would expect the same thing as @JulianJorgensen (begin at 1) even though your explanation makes sense, technically.

**Comment by jscottsmith** [comment]
@PTcampbell thanks for explaining your use case. I'll have to think more about what an implementation that supports this would look like. 

There would need to be a way to declare what portion of the screen the element will be active in for each style prop (`x`, `y`, `opacity` & `scale`). Then this given range would need to affect each style prop independently of the others. For your use case it would be the `opacity` style prop on the bottom half of the screen.

Definitely complicates things and I'm hesitant to take it in this direction at the moment. If you have ideas please share.

**Comment by PTcampbell** [comment]
No worries. One other thing to consider is that with the current method you could never entirely fade in an element at the bottom of the page, such as the footer. Basically I think you would need a way of specifying at which point the animation starts, e.g. the top of the viewport, the bottom, etc. akin to how it's handled with `[this plugin.](https://github.com/jlmakes/scrollreveal )`.

**Comment by jscottsmith** [comment]
Ya I see what you're saying, but does the animation timing need to be tied to scroll? I think an effect like the one you describe is best handled by a class and CSS transition. You could also easily do that with this library because the `<Parallax>` component provides a boolean for when the element is in view via a child function. 

Here's an example:

```jsx
<Parallax>
    {({ isInView }) =>
        <div className={isInView ? 'foo in-view' : 'foo'} />
    }
</Parallax>
```
and the CSS:

```css
.foo {
    opacity: 0;
    transition: opacity 1s;
}

.in-view {
    opacity: 1;
}
```

**Comment by csantiago132** [comment]
im going to make a branch and play with this release and see how it goes, ill try what you mentioned above @jscottsmith and see if it breaks anything. what should we be looking out for?  just in case we can notice something you need to be brought up

**Comment by PTcampbell** [comment]
I can imagine that some folks would prefer the animation to be tied to scroll, and others not. In my case your suggestion would work just fine. I ended up using [aos.js](https://github.com/michalsnik/aos) in tandem with your library for the parallax.

**Comment by jscottsmith** [comment]
@PTcampbell great, glad that helps in your case. I'll keep thinking about the original request, it's certainly a valid use case. 

@csantiago132 try it out and if you notice any bugs or performance issues please report them. I'm also open to discussion of features or changes to the API since this is just an Alpha release. Check out the [README](https://github.com/jscottsmith/react-scroll-parallax/tree/v2) for usage instructions. It's pretty straight forward, but if there's confusion let me know.

**Comment by oyeanuj** [comment]
@jscottsmith Curious how `ParallaxProvider` works with SSR? 

+1 for components like `ParallaxImage`, and internal component like `Observed`.

**Comment by oyeanuj** [comment]
@jscottsmith Just tried v2 and it worked smoothly. Thank you! Just one query - 

Is there a way to control the duration of the scroll - or does it just go from 0% visible to 100% visible (and vice versa)? My usecase is to just have a slight slide up animation when the image enters the viewport.

+1 for components like ParallaxImage, and internal component like `Observed`.

**Comment by jscottsmith** [comment]
@oyeanuj It will go from `0–1`; see the discussion above for details. 

I would again suggest a class based CSS transition for this type of use case. [See this example](https://github.com/jscottsmith/react-scroll-parallax/issues/15#issuecomment-353681835), but replace opacity with a transform. 

I'll add an export for `<Observed>` in this lib but if all you're doing is triggering animation when in view you can just use the standalone [Observed component here](https://github.com/jscottsmith/react-observed).

**Comment by c0d3ster** [comment]
Great progress on the repo; it's awesome to see that you're actively working on getting the v2 beta out!  This is what swayed my decision to choose this repo over react-parallax.  Once I get the current version implemented into my project, I'd be happy to help with some of these v2 objectives :)

**Comment by jscottsmith** [comment]
@c0d3ster Thanks, help would certainly be welcome.

**Comment by calsal8** [comment]
Thank you for working on this repo! 
Not sure if I've missed something but I would like to change scroll rate to a higher value so that the element moves faster without affecting the offset. I've set sloweScrollRate to false to make the element move upwards on scroll down. To make it move faster I've set `offsetYMax` to 1000 and `offsetYMin` to -1000, but that also affects the animation when it's not in the viewport. Would it be possible to add a prop `scrollRate` that sets how much the element will move according to scroll? Like a multiplier.

**Comment by jscottsmith** [comment]
@calsal8 ya I think you misunderstand how the library is designed to work, or I don't understand the problem. The offsets are used to give an element the varying appearance of scroll speed. Increase the offsets the more the dramatic the effect.

Not sure if the question is meant to relate to v2 since you're referencing the v1 API. If you're having trouble with implementation open a new ticket and I can help you out there, as I'd like this ticket to be used for discussing v2. Thanks!

**Comment by VilhelmNielsen** [comment]
Why is styleInner, styleOuter and Tag props omitted from v2 alpha?

**Comment by csantiago132** [comment]
@VilhelmNielsen I think theyre still there, this is inspecting the Storybook link at the top. 
```html
<div   /* pretty sure this is the tag prop */
  class="parallax-element"  /* style outer */
  style="opacity: 1; 
  transform: translate3d(0px, 7.23562%, 0px) scale(1);"
>
  <div class="Element_ratio_CFS">
    <div class="Element_inner_2b0">  /* style inner */
      <div class="Element_box_S2F"> 
        An Element
      </div>
    </div>
  </div>
</div>  /*end of the tag prop */
````
Since hes working on this now, let him do his thing and lets see how everything will be handled. im prettu sure he'll explain all this when hes done

**Comment by VilhelmNielsen** [comment]
@csantiago132 Apologies if my comment sounded harsh or demanding. Migrating from v1 to v2-alpha, none of those three props seem to work, so my question was seeking answers as to whether the API around these were changing or whether they just aren't implemented yet. The props seem to be omitted from the v2 docs, so I thought clarification was necessary, so any one can help out with the development.

I will try to fork this branch and see, if I can perhaps reimplement these features.

I don't see how inspecting HTML elements clarify React props, but perhaps we are misunderstanding each-other.

**Comment by csantiago132** [comment]
@VilhelmNielsen no offense, not at all and just trying to help out. From inspecting/playing with the storybook, I can assume theyre there, maybe not! I havent mess around with the alpha release so I honestly cant tell. Maybe he will change the API, maybe not, thats all im trying to say

**Comment by jscottsmith** [comment]
Closing this because the alpha has performance issues with moving things to state. Working on another branch to hopefully address some of these features in a more performant way.

**Comment by vasilevach** [comment]
> Ya I see what you're saying, but does the animation timing need to be tied to scroll? I think an effect like the one you describe is best handled by a class and CSS transition. You could also easily do that with this library because the `<Parallax>` component provides a boolean for when the element is in view via a child function.
> 
> Here's an example:
> 
> ```js-jsx
> <Parallax>
>     {({ isInView }) =>
>         <div className={isInView ? 'foo in-view' : 'foo'} />
>     }
> </Parallax>
> ```
> 
> and the CSS:
> 
> ```css
> .foo {
>     opacity: 0;
>     transition: opacity 1s;
> }
> 
> .in-view {
>     opacity: 1;
> }
> ```

Hey @jscottsmith did you remove the render props functionality? React gives me an error when I try to use it:

```
Warning: Failed prop type: Invalid prop `children` supplied to `Parallax`, expected a ReactNode.
```

v. 2.3.2

**Comment by jscottsmith** [comment]
@vasilevach There's no render prop in the current v2. This direction was abandoned because of some performance issues. See the [docs](https://github.com/jscottsmith/react-scroll-parallax#react-scroll-parallax) for current functionality.

**Comment by vasilevach** [comment]
Oh, that's a shame :) Thanks for the answer! I will think of an alternative :)

**Comment by goodluck19970821** [comment]
Hi, @ jscottsmith.
I am very sad. I wanted to use opacity control with vertical and horizontal control simultaneously.

**Comment by jscottsmith** [comment]
@goodluck19970821 Apologies... If I ever get some more free time I'd love to add support for this type of feature.
